### ISSUE TITLE
Forward / Backports

### ISSUE THREAD

**Issue by rousseldenis** [OCA/odoo-pim#10]
# Forward port from 10.0 to 12.0

* [x] https://github.com/shopinvader/odoo-pim/pull/37 - By @simahawk - #48
* [x] https://github.com/shopinvader/odoo-pim/pull/38 - By @simahawk - #50
* [x] https://github.com/shopinvader/odoo-pim/pull/43 - By @simahawk - #49
* [x] https://github.com/shopinvader/odoo-pim/pull/44 - By @simahawk - #54 
* [x] https://github.com/shopinvader/odoo-pim/pull/45 - By @simahawk - #51
* [x] https://github.com/shopinvader/odoo-pim/pull/46 - By @simahawk - #52
* [x] https://github.com/shopinvader/odoo-pim/pull/47 - By @simahawk - #53

# Back port from 12.0 to 10.0

* [x] attribute_set - By @rousseldenis - #13 
* [x] pim
* [x] pim_attribute_set
* [x] product_attribute_set

**Comment by rousseldenis** [comment]
For v10 backport, suggested to merge pim and pim_attribute_set @lmignon @Cedric-Pigeon

**Comment by Cedric-Pigeon** [comment]
@rousseldenis addons merge done on V12.0
