### ISSUE TITLE
After install : nothing

### ISSUE THREAD

**Issue by darkiron** [OCA/odoo-pim#121]
Follow general instruction for install plugin in docker for odoo 14. No application found  in app dashboard

## Module
pim

## Describe the bug
No app in list

## To Reproduce
**Affected versions**: Odoo 14.0-20220609 (Community Edition)

1. install plugin
2. reboot docker env
3. show

**Expected behavior**
found app in app dashboard

**Additional context**
docker image

**Comment by pjrobertson** [comment]
How are you installing the plugin? The instructions in the readme seem very basic

**Comment by dnplkndll** [comment]
need to assign the pim manager role?
