### ISSUE TITLE
RFC Use new odoo native property feature to improve PIM usability

### ISSUE THREAD

**Issue by bealdav** [OCA/odoo-pim#161]
## Is your feature request related to a problem?

Pim is a great innovative but new feature in odoo, property, could improve the usability of the modules suite

## Describe the solution you'd like
Here is an example of the feature on project / tasks 
Settings in project
https://github.com/odoo/odoo/blob/16.0/addons/project/models/project.py#L368

Concrete fields in task
https://github.com/odoo/odoo/blob/16.0/addons/project/models/project.py#L1135

Just test it on runbot, in a task with property link.

We may easily imagine how to apply this principle on `product.product`.

attribute.set or other object may keep the settings according to kind of product

These properties are very flexible and easy to use and benefit of advanced postgres features.

## Describe alternatives you've considered

Keep PIM as it, but ui is complex.

We could also use pim current way and new way available, experiments will answer us which is the best.

cc @sebastienbeau @rvalyi @clementmbr @Cedric-Pigeon @rousseldenis @PierrickBrun

**Comment by rousseldenis** [comment]
@bealdav I think this is a track that should be evaluated. Do you go to spanish OCA days ? I think @sebastienbeau will be there. @marielejeune @AnizR maybe a good point to discuss

**Comment by bealdav** [comment]
Thanks to spread the word. Sorry I'll not join you in spain, sadly.

**Comment by Cedric-Pigeon** [comment]
@bealdav yes it is a good idea in my opinion. We hire a trainee for a couple of weeks on the PIM. You can have a look on his work here: https://github.com/OCA/odoo-pim/issues/153 Comments are kindly welcome ;-)
