### ISSUE TITLE
product m2m attr: Uncaught TypeError: Cannot read property 'list' of undefined

### ISSUE THREAD

**Issue by rvalyi** [OCA/odoo-pim#2]
with the current product_custom_attribute module, if you add some many2many attribute (here the `multi` field) in your attribute_set, it seems that for any attribute of the form, you will have the following javascript error triggered with the onchange event.

```
web.assets_backend.js:2142 Uncaught TypeError: Cannot read property 'list' of undefined
    at web.assets_backend.js:2142
    at Function._.each._.forEach (web.assets_common.js:12)
    at web.assets_backend.js:2142
    at Function._.each._.forEach (web.assets_common.js:12)
    at Class._build_onchange_specs (web.assets_backend.js:2142)
    at Class.do_onchange (web.assets_backend.js:2145)
    at Class.<anonymous> (web.assets_backend.js:2189)
    at Class.trigger (web.assets_common.js:3105)
    at Class.trigger (web.assets_common.js:3109)
    at Class.<anonymous> (web.assets_backend.js:2229)
```

![Screenshot from 2019-05-22 09-50-05](https://user-images.githubusercontent.com/16926/58175662-05b1c680-7c77-11e9-9d2e-f9b871076fab.png)

Moreover, with @sebastienbeau we were talking about changing the m2m widget as a many2many_tags widget. Well it happens that using the many2many_tags widget avoids this bug yet I have no idea why. So eventually we have a widget field to specify the attribute widget, but I suggest that as a first approach we simply use the many2many_tags widget as default as it avoids this bug.

**Comment by mwadea** [comment]
Hello @rvalyi 

I am trying to add an m2m field as an attribute but I am trying to add it in the view as a table with more than one column for example:
**network interfaces**
| seq | mac address | speed |
|------|-------------------|----------|
| 1    | xx:xx:xx:xx    | 1G |
|add line                         |

I thinking that maybe I can create every column as a seperate attribute and link them all in one m2m

I am posting this question here as I can see that in the original post you have a table in the product view similar to what I am trying to achieve. 
If this is possible using the current module please advise me on how to do it..

Thanks
