### ISSUE TITLE
[13.0] attribute_set_mass_edit: does not work for selection fields

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/odoo-pim#58]
in mass edition, values for "Select" attributes are mixed.

Given the following attribute:

![image](https://user-images.githubusercontent.com/7813258/95570581-6934c380-0a27-11eb-80df-112f82344ac9.png)

And this one:

![image](https://user-images.githubusercontent.com/7813258/95570611-75208580-0a27-11eb-9274-99770cf84c8d.png)

When I try to mass edit the color, the processors appear in the possible values:

![image](https://user-images.githubusercontent.com/7813258/95570671-88335580-0a27-11eb-939d-99107819be03.png)

I do not think it is related to migration.

**Comment by simahawk** [comment]
@Cedric-Pigeon is this still an issue?
