### ISSUE TITLE
[12.0] impossible to fill pim_default_product_attribute_set_id

### ISSUE THREAD

**Issue by clementmbr** [OCA/odoo-pim#61]
Hi,

In the menu _PIM > Settings > Configuration_ there is a **Default Product Attribute Set** field impossible to fill.
It is related to company_id's `product_default_attribute_set_id` but [this field](https://github.com/shopinvader/odoo-pim/blob/12.0/product_attribute_set/models/res_company.py#L11) doesn't appear in any view and is not filled by any method.

What is the imagined process around this **Default Product Attribute Set** ?

Cc @rousseldenis @simahawk

**Comment by simahawk** [comment]
Blind fix, but I bet that's your issue :)
https://github.com/shopinvader/odoo-pim/pull/62
