### ISSUE TITLE
Maintain variant specific PIM attributes

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/odoo-pim#95]
We are faced with the requirement to maintain variant specific PIM attributes. At this moment the whole PIM is designed so as to maintain the attribute.attribute records as being associated to the product.template.

We could always create a variant attribute set and maintain variant-specific attributes this way.

Perhaps you've come across this requirement before?

**Comment by CasVissers-360ERP** [comment]
We are facing a similar issue, it's also a bit confusing that attribute_set_id is available on the product.product form view and when setting it the page product_attributes becomes visible without any attributes. 

Would be nice to also trigger the onchanges from product.product. I think this is not what @JordiBForgeFlow is suggesting. But maybe the solution could be to set the attributes on product.product level, if there is 1-1 relation between product.template and product.product the attributes should be ok?
